apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-mcp-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dongmin3891/home-mcp-server.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
